// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddHospital mocks base method.
func (m *MockRepository) AddHospital(ctx context.Context, hospital domain.Hospital) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHospital", ctx, hospital)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHospital indicates an expected call of AddHospital.
func (mr *MockRepositoryMockRecorder) AddHospital(ctx, hospital any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHospital", reflect.TypeOf((*MockRepository)(nil).AddHospital), ctx, hospital)
}

// AddHospitalAssignment mocks base method.
func (m *MockRepository) AddHospitalAssignment(ctx context.Context, assignment domain.HospitalAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddHospitalAssignment", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddHospitalAssignment indicates an expected call of AddHospitalAssignment.
func (mr *MockRepositoryMockRecorder) AddHospitalAssignment(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHospitalAssignment", reflect.TypeOf((*MockRepository)(nil).AddHospitalAssignment), ctx, assignment)
}

// ArchiveHospital mocks base method.
func (m *MockRepository) ArchiveHospital(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveHospital", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveHospital indicates an expected call of ArchiveHospital.
func (mr *MockRepositoryMockRecorder) ArchiveHospital(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveHospital", reflect.TypeOf((*MockRepository)(nil).ArchiveHospital), ctx, id)
}

// GetHospitalAssignmentByID mocks base method.
func (m *MockRepository) GetHospitalAssignmentByID(ctx context.Context, id string) (*domain.HospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitalAssignmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.HospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitalAssignmentByID indicates an expected call of GetHospitalAssignmentByID.
func (mr *MockRepositoryMockRecorder) GetHospitalAssignmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitalAssignmentByID", reflect.TypeOf((*MockRepository)(nil).GetHospitalAssignmentByID), ctx, id)
}

// GetHospitalAssignments mocks base method.
func (m *MockRepository) GetHospitalAssignments(ctx context.Context, limit int) ([]domain.HospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitalAssignments", ctx, limit)
	ret0, _ := ret[0].([]domain.HospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitalAssignments indicates an expected call of GetHospitalAssignments.
func (mr *MockRepositoryMockRecorder) GetHospitalAssignments(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitalAssignments", reflect.TypeOf((*MockRepository)(nil).GetHospitalAssignments), ctx, limit)
}

// GetHospitalByID mocks base method.
func (m *MockRepository) GetHospitalByID(ctx context.Context, id string) (*domain.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitalByID", ctx, id)
	ret0, _ := ret[0].(*domain.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitalByID indicates an expected call of GetHospitalByID.
func (mr *MockRepositoryMockRecorder) GetHospitalByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitalByID", reflect.TypeOf((*MockRepository)(nil).GetHospitalByID), ctx, id)
}

// GetHospitalIDByAccountID mocks base method.
func (m *MockRepository) GetHospitalIDByAccountID(ctx context.Context, accountID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitalIDByAccountID", ctx, accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitalIDByAccountID indicates an expected call of GetHospitalIDByAccountID.
func (mr *MockRepositoryMockRecorder) GetHospitalIDByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitalIDByAccountID", reflect.TypeOf((*MockRepository)(nil).GetHospitalIDByAccountID), ctx, accountID)
}

// GetHospitals mocks base method.
func (m *MockRepository) GetHospitals(ctx context.Context, limit int) ([]domain.Hospital, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitals", ctx, limit)
	ret0, _ := ret[0].([]domain.Hospital)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitals indicates an expected call of GetHospitals.
func (mr *MockRepositoryMockRecorder) GetHospitals(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitals", reflect.TypeOf((*MockRepository)(nil).GetHospitals), ctx, limit)
}

// RemoveHospitalToAccountAssignment mocks base method.
func (m *MockRepository) RemoveHospitalToAccountAssignment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHospitalToAccountAssignment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHospitalToAccountAssignment indicates an expected call of RemoveHospitalToAccountAssignment.
func (mr *MockRepositoryMockRecorder) RemoveHospitalToAccountAssignment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHospitalToAccountAssignment", reflect.TypeOf((*MockRepository)(nil).RemoveHospitalToAccountAssignment), ctx, id)
}

// ResetHospitals mocks base method.
func (m *MockRepository) ResetHospitals(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetHospitals", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetHospitals indicates an expected call of ResetHospitals.
func (mr *MockRepositoryMockRecorder) ResetHospitals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetHospitals", reflect.TypeOf((*MockRepository)(nil).ResetHospitals), ctx)
}

// UpdateHospital mocks base method.
func (m *MockRepository) UpdateHospital(ctx context.Context, hospital domain.Hospital) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateHospital", ctx, hospital)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateHospital indicates an expected call of UpdateHospital.
func (mr *MockRepositoryMockRecorder) UpdateHospital(ctx, hospital any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateHospital", reflect.TypeOf((*MockRepository)(nil).UpdateHospital), ctx, hospital)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
