// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAccountSVC is a mock of AccountSVC interface.
type MockAccountSVC struct {
	ctrl     *gomock.Controller
	recorder *MockAccountSVCMockRecorder
	isgomock struct{}
}

// MockAccountSVCMockRecorder is the mock recorder for MockAccountSVC.
type MockAccountSVCMockRecorder struct {
	mock *MockAccountSVC
}

// NewMockAccountSVC creates a new mock instance.
func NewMockAccountSVC(ctrl *gomock.Controller) *MockAccountSVC {
	mock := &MockAccountSVC{ctrl: ctrl}
	mock.recorder = &MockAccountSVCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAccountSVC) EXPECT() *MockAccountSVCMockRecorder {
	return m.recorder
}

// CreateAccount mocks base method.
func (m *MockAccountSVC) CreateAccount(ctx context.Context, account domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccount indicates an expected call of CreateAccount.
func (mr *MockAccountSVCMockRecorder) CreateAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccount", reflect.TypeOf((*MockAccountSVC)(nil).CreateAccount), ctx, account)
}

// GetAccountByID mocks base method.
func (m *MockAccountSVC) GetAccountByID(ctx context.Context, id string) (*domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountByID", ctx, id)
	ret0, _ := ret[0].(*domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountByID indicates an expected call of GetAccountByID.
func (mr *MockAccountSVCMockRecorder) GetAccountByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountByID", reflect.TypeOf((*MockAccountSVC)(nil).GetAccountByID), ctx, id)
}

// GetAccounts mocks base method.
func (m *MockAccountSVC) GetAccounts(ctx context.Context, limit int) ([]domain.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccounts", ctx, limit)
	ret0, _ := ret[0].([]domain.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccounts indicates an expected call of GetAccounts.
func (mr *MockAccountSVCMockRecorder) GetAccounts(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccounts", reflect.TypeOf((*MockAccountSVC)(nil).GetAccounts), ctx, limit)
}

// UpdateAccount mocks base method.
func (m *MockAccountSVC) UpdateAccount(ctx context.Context, account domain.Account) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccount", ctx, account)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccount indicates an expected call of UpdateAccount.
func (mr *MockAccountSVCMockRecorder) UpdateAccount(ctx, account any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccount", reflect.TypeOf((*MockAccountSVC)(nil).UpdateAccount), ctx, account)
}
