// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddTuple mocks base method.
func (m *MockClient) AddTuple(ctx context.Context, tuple domain.Tuple) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTuple", ctx, tuple)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTuple indicates an expected call of AddTuple.
func (mr *MockClientMockRecorder) AddTuple(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTuple", reflect.TypeOf((*MockClient)(nil).AddTuple), ctx, tuple)
}

// RemoveTuple mocks base method.
func (m *MockClient) RemoveTuple(ctx context.Context, tuple domain.Tuple) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTuple", ctx, tuple)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTuple indicates an expected call of RemoveTuple.
func (mr *MockClientMockRecorder) RemoveTuple(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTuple", reflect.TypeOf((*MockClient)(nil).RemoveTuple), ctx, tuple)
}
