// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOpenFGA is a mock of OpenFGA interface.
type MockOpenFGA struct {
	ctrl     *gomock.Controller
	recorder *MockOpenFGAMockRecorder
	isgomock struct{}
}

// MockOpenFGAMockRecorder is the mock recorder for MockOpenFGA.
type MockOpenFGAMockRecorder struct {
	mock *MockOpenFGA
}

// NewMockOpenFGA creates a new mock instance.
func NewMockOpenFGA(ctrl *gomock.Controller) *MockOpenFGA {
	mock := &MockOpenFGA{ctrl: ctrl}
	mock.recorder = &MockOpenFGAMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenFGA) EXPECT() *MockOpenFGAMockRecorder {
	return m.recorder
}

// AddTuple mocks base method.
func (m *MockOpenFGA) AddTuple(ctx context.Context, tuple domain.Tuple) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTuple", ctx, tuple)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTuple indicates an expected call of AddTuple.
func (mr *MockOpenFGAMockRecorder) AddTuple(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTuple", reflect.TypeOf((*MockOpenFGA)(nil).AddTuple), ctx, tuple)
}

// Check mocks base method.
func (m *MockOpenFGA) Check(ctx context.Context, tuple domain.Tuple) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, tuple)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockOpenFGAMockRecorder) Check(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockOpenFGA)(nil).Check), ctx, tuple)
}

// RemoveTuple mocks base method.
func (m *MockOpenFGA) RemoveTuple(ctx context.Context, tuple domain.Tuple) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTuple", ctx, tuple)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTuple indicates an expected call of RemoveTuple.
func (mr *MockOpenFGAMockRecorder) RemoveTuple(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTuple", reflect.TypeOf((*MockOpenFGA)(nil).RemoveTuple), ctx, tuple)
}
