// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	event "openhealth/internal/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddOutboxEvent mocks base method.
func (m *MockRepository) AddOutboxEvent(ctx context.Context, outboxEvent event.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOutboxEvent", ctx, outboxEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOutboxEvent indicates an expected call of AddOutboxEvent.
func (mr *MockRepositoryMockRecorder) AddOutboxEvent(ctx, outboxEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOutboxEvent", reflect.TypeOf((*MockRepository)(nil).AddOutboxEvent), ctx, outboxEvent)
}

// GetPendingOutboxEvents mocks base method.
func (m *MockRepository) GetPendingOutboxEvents(ctx context.Context, limit int) ([]event.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingOutboxEvents", ctx, limit)
	ret0, _ := ret[0].([]event.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingOutboxEvents indicates an expected call of GetPendingOutboxEvents.
func (mr *MockRepositoryMockRecorder) GetPendingOutboxEvents(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingOutboxEvents", reflect.TypeOf((*MockRepository)(nil).GetPendingOutboxEvents), ctx, limit)
}

// UpdateOutboxEventStatus mocks base method.
func (m *MockRepository) UpdateOutboxEventStatus(ctx context.Context, id string, status event.OutboxEventStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOutboxEventStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateOutboxEventStatus indicates an expected call of UpdateOutboxEventStatus.
func (mr *MockRepositoryMockRecorder) UpdateOutboxEventStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOutboxEventStatus", reflect.TypeOf((*MockRepository)(nil).UpdateOutboxEventStatus), ctx, id, status)
}
