// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddNurse mocks base method.
func (m *MockRepository) AddNurse(ctx context.Context, nurse domain.Nurse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNurse", ctx, nurse)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNurse indicates an expected call of AddNurse.
func (mr *MockRepositoryMockRecorder) AddNurse(ctx, nurse any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNurse", reflect.TypeOf((*MockRepository)(nil).AddNurse), ctx, nurse)
}

// AddNurseToHospitalAssignment mocks base method.
func (m *MockRepository) AddNurseToHospitalAssignment(ctx context.Context, assignment domain.NurseToHospitalAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNurseToHospitalAssignment", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNurseToHospitalAssignment indicates an expected call of AddNurseToHospitalAssignment.
func (mr *MockRepositoryMockRecorder) AddNurseToHospitalAssignment(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNurseToHospitalAssignment", reflect.TypeOf((*MockRepository)(nil).AddNurseToHospitalAssignment), ctx, assignment)
}

// GetHospitalIDByNurseID mocks base method.
func (m *MockRepository) GetHospitalIDByNurseID(ctx context.Context, nurseID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHospitalIDByNurseID", ctx, nurseID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHospitalIDByNurseID indicates an expected call of GetHospitalIDByNurseID.
func (mr *MockRepositoryMockRecorder) GetHospitalIDByNurseID(ctx, nurseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHospitalIDByNurseID", reflect.TypeOf((*MockRepository)(nil).GetHospitalIDByNurseID), ctx, nurseID)
}

// GetNurseByAccountID mocks base method.
func (m *MockRepository) GetNurseByAccountID(ctx context.Context, accountID string) (*domain.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseByAccountID", ctx, accountID)
	ret0, _ := ret[0].(*domain.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseByAccountID indicates an expected call of GetNurseByAccountID.
func (mr *MockRepositoryMockRecorder) GetNurseByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseByAccountID", reflect.TypeOf((*MockRepository)(nil).GetNurseByAccountID), ctx, accountID)
}

// GetNurseByID mocks base method.
func (m *MockRepository) GetNurseByID(ctx context.Context, id string) (*domain.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseByID", ctx, id)
	ret0, _ := ret[0].(*domain.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseByID indicates an expected call of GetNurseByID.
func (mr *MockRepositoryMockRecorder) GetNurseByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseByID", reflect.TypeOf((*MockRepository)(nil).GetNurseByID), ctx, id)
}

// GetNurseToHospitalAssignmentByID mocks base method.
func (m *MockRepository) GetNurseToHospitalAssignmentByID(ctx context.Context, id string) (*domain.NurseToHospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseToHospitalAssignmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.NurseToHospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseToHospitalAssignmentByID indicates an expected call of GetNurseToHospitalAssignmentByID.
func (mr *MockRepositoryMockRecorder) GetNurseToHospitalAssignmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseToHospitalAssignmentByID", reflect.TypeOf((*MockRepository)(nil).GetNurseToHospitalAssignmentByID), ctx, id)
}

// GetNurseToHospitalAssignments mocks base method.
func (m *MockRepository) GetNurseToHospitalAssignments(ctx context.Context, limit int) ([]domain.NurseToHospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseToHospitalAssignments", ctx, limit)
	ret0, _ := ret[0].([]domain.NurseToHospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseToHospitalAssignments indicates an expected call of GetNurseToHospitalAssignments.
func (mr *MockRepositoryMockRecorder) GetNurseToHospitalAssignments(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseToHospitalAssignments", reflect.TypeOf((*MockRepository)(nil).GetNurseToHospitalAssignments), ctx, limit)
}

// GetNurseToHospitalAssignmentsByNurseID mocks base method.
func (m *MockRepository) GetNurseToHospitalAssignmentsByNurseID(ctx context.Context, nurseID string) ([]domain.NurseToHospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurseToHospitalAssignmentsByNurseID", ctx, nurseID)
	ret0, _ := ret[0].([]domain.NurseToHospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurseToHospitalAssignmentsByNurseID indicates an expected call of GetNurseToHospitalAssignmentsByNurseID.
func (mr *MockRepositoryMockRecorder) GetNurseToHospitalAssignmentsByNurseID(ctx, nurseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurseToHospitalAssignmentsByNurseID", reflect.TypeOf((*MockRepository)(nil).GetNurseToHospitalAssignmentsByNurseID), ctx, nurseID)
}

// GetNurses mocks base method.
func (m *MockRepository) GetNurses(ctx context.Context, limit int) ([]domain.Nurse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNurses", ctx, limit)
	ret0, _ := ret[0].([]domain.Nurse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNurses indicates an expected call of GetNurses.
func (mr *MockRepositoryMockRecorder) GetNurses(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNurses", reflect.TypeOf((*MockRepository)(nil).GetNurses), ctx, limit)
}

// GetNursesByHospitalID mocks base method.
func (m *MockRepository) GetNursesByHospitalID(ctx context.Context, hospitalID string) ([]domain.NurseToHospitalAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNursesByHospitalID", ctx, hospitalID)
	ret0, _ := ret[0].([]domain.NurseToHospitalAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNursesByHospitalID indicates an expected call of GetNursesByHospitalID.
func (mr *MockRepositoryMockRecorder) GetNursesByHospitalID(ctx, hospitalID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNursesByHospitalID", reflect.TypeOf((*MockRepository)(nil).GetNursesByHospitalID), ctx, hospitalID)
}

// RemoveAllNurseToHospitalAssignments mocks base method.
func (m *MockRepository) RemoveAllNurseToHospitalAssignments(ctx context.Context, nurseID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllNurseToHospitalAssignments", ctx, nurseID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllNurseToHospitalAssignments indicates an expected call of RemoveAllNurseToHospitalAssignments.
func (mr *MockRepositoryMockRecorder) RemoveAllNurseToHospitalAssignments(ctx, nurseID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllNurseToHospitalAssignments", reflect.TypeOf((*MockRepository)(nil).RemoveAllNurseToHospitalAssignments), ctx, nurseID)
}

// RemoveNurseToHospitalAssignment mocks base method.
func (m *MockRepository) RemoveNurseToHospitalAssignment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveNurseToHospitalAssignment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveNurseToHospitalAssignment indicates an expected call of RemoveNurseToHospitalAssignment.
func (mr *MockRepositoryMockRecorder) RemoveNurseToHospitalAssignment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveNurseToHospitalAssignment", reflect.TypeOf((*MockRepository)(nil).RemoveNurseToHospitalAssignment), ctx, id)
}

// UpdateNurseStatusByID mocks base method.
func (m *MockRepository) UpdateNurseStatusByID(ctx context.Context, id string, status domain.NurseStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNurseStatusByID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNurseStatusByID indicates an expected call of UpdateNurseStatusByID.
func (mr *MockRepositoryMockRecorder) UpdateNurseStatusByID(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNurseStatusByID", reflect.TypeOf((*MockRepository)(nil).UpdateNurseStatusByID), ctx, id, status)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
