// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddDoctor mocks base method.
func (m *MockRepository) AddDoctor(ctx context.Context, doctor domain.Doctor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDoctor", ctx, doctor)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDoctor indicates an expected call of AddDoctor.
func (mr *MockRepositoryMockRecorder) AddDoctor(ctx, doctor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDoctor", reflect.TypeOf((*MockRepository)(nil).AddDoctor), ctx, doctor)
}

// AssignDoctorToAccount mocks base method.
func (m *MockRepository) AssignDoctorToAccount(ctx context.Context, accountID, doctorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignDoctorToAccount", ctx, accountID, doctorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignDoctorToAccount indicates an expected call of AssignDoctorToAccount.
func (mr *MockRepositoryMockRecorder) AssignDoctorToAccount(ctx, accountID, doctorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignDoctorToAccount", reflect.TypeOf((*MockRepository)(nil).AssignDoctorToAccount), ctx, accountID, doctorID)
}

// ExpireDoctorAssignments mocks base method.
func (m *MockRepository) ExpireDoctorAssignments(ctx context.Context, doctorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpireDoctorAssignments", ctx, doctorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExpireDoctorAssignments indicates an expected call of ExpireDoctorAssignments.
func (mr *MockRepositoryMockRecorder) ExpireDoctorAssignments(ctx, doctorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpireDoctorAssignments", reflect.TypeOf((*MockRepository)(nil).ExpireDoctorAssignments), ctx, doctorID)
}

// GetDoctorByID mocks base method.
func (m *MockRepository) GetDoctorByID(ctx context.Context, id string) (*domain.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorByID", ctx, id)
	ret0, _ := ret[0].(*domain.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorByID indicates an expected call of GetDoctorByID.
func (mr *MockRepositoryMockRecorder) GetDoctorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorByID", reflect.TypeOf((*MockRepository)(nil).GetDoctorByID), ctx, id)
}

// GetDoctors mocks base method.
func (m *MockRepository) GetDoctors(ctx context.Context, limit int) ([]domain.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctors", ctx, limit)
	ret0, _ := ret[0].([]domain.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctors indicates an expected call of GetDoctors.
func (mr *MockRepositoryMockRecorder) GetDoctors(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctors", reflect.TypeOf((*MockRepository)(nil).GetDoctors), ctx, limit)
}

// UpdateDoctorStatusByID mocks base method.
func (m *MockRepository) UpdateDoctorStatusByID(ctx context.Context, id string, status domain.DoctorStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDoctorStatusByID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDoctorStatusByID indicates an expected call of UpdateDoctorStatusByID.
func (mr *MockRepositoryMockRecorder) UpdateDoctorStatusByID(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDoctorStatusByID", reflect.TypeOf((*MockRepository)(nil).UpdateDoctorStatusByID), ctx, id, status)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
