// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	event "openhealth/internal/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddDoctor mocks base method.
func (m *MockRepository) AddDoctor(ctx context.Context, doctor domain.Doctor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDoctor", ctx, doctor)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDoctor indicates an expected call of AddDoctor.
func (mr *MockRepositoryMockRecorder) AddDoctor(ctx, doctor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDoctor", reflect.TypeOf((*MockRepository)(nil).AddDoctor), ctx, doctor)
}

// AddDoctorToAccountAssignment mocks base method.
func (m *MockRepository) AddDoctorToAccountAssignment(ctx context.Context, assignment domain.DoctorAssignment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDoctorToAccountAssignment", ctx, assignment)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDoctorToAccountAssignment indicates an expected call of AddDoctorToAccountAssignment.
func (mr *MockRepositoryMockRecorder) AddDoctorToAccountAssignment(ctx, assignment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDoctorToAccountAssignment", reflect.TypeOf((*MockRepository)(nil).AddDoctorToAccountAssignment), ctx, assignment)
}

// AddOutboxEvent mocks base method.
func (m *MockRepository) AddOutboxEvent(ctx context.Context, outboxEvent event.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOutboxEvent", ctx, outboxEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOutboxEvent indicates an expected call of AddOutboxEvent.
func (mr *MockRepositoryMockRecorder) AddOutboxEvent(ctx, outboxEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOutboxEvent", reflect.TypeOf((*MockRepository)(nil).AddOutboxEvent), ctx, outboxEvent)
}

// GetDoctorAssignmentByID mocks base method.
func (m *MockRepository) GetDoctorAssignmentByID(ctx context.Context, id string) (*domain.DoctorAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorAssignmentByID", ctx, id)
	ret0, _ := ret[0].(*domain.DoctorAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorAssignmentByID indicates an expected call of GetDoctorAssignmentByID.
func (mr *MockRepositoryMockRecorder) GetDoctorAssignmentByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorAssignmentByID", reflect.TypeOf((*MockRepository)(nil).GetDoctorAssignmentByID), ctx, id)
}

// GetDoctorAssignments mocks base method.
func (m *MockRepository) GetDoctorAssignments(ctx context.Context, limit int) ([]domain.DoctorAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorAssignments", ctx, limit)
	ret0, _ := ret[0].([]domain.DoctorAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorAssignments indicates an expected call of GetDoctorAssignments.
func (mr *MockRepositoryMockRecorder) GetDoctorAssignments(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorAssignments", reflect.TypeOf((*MockRepository)(nil).GetDoctorAssignments), ctx, limit)
}

// GetDoctorAssignmentsByDoctorID mocks base method.
func (m *MockRepository) GetDoctorAssignmentsByDoctorID(ctx context.Context, doctorID string) ([]domain.DoctorAssignment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorAssignmentsByDoctorID", ctx, doctorID)
	ret0, _ := ret[0].([]domain.DoctorAssignment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorAssignmentsByDoctorID indicates an expected call of GetDoctorAssignmentsByDoctorID.
func (mr *MockRepositoryMockRecorder) GetDoctorAssignmentsByDoctorID(ctx, doctorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorAssignmentsByDoctorID", reflect.TypeOf((*MockRepository)(nil).GetDoctorAssignmentsByDoctorID), ctx, doctorID)
}

// GetDoctorByAccountID mocks base method.
func (m *MockRepository) GetDoctorByAccountID(ctx context.Context, accountID string) (*domain.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorByAccountID", ctx, accountID)
	ret0, _ := ret[0].(*domain.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorByAccountID indicates an expected call of GetDoctorByAccountID.
func (mr *MockRepositoryMockRecorder) GetDoctorByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorByAccountID", reflect.TypeOf((*MockRepository)(nil).GetDoctorByAccountID), ctx, accountID)
}

// GetDoctorByID mocks base method.
func (m *MockRepository) GetDoctorByID(ctx context.Context, id string) (*domain.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorByID", ctx, id)
	ret0, _ := ret[0].(*domain.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorByID indicates an expected call of GetDoctorByID.
func (mr *MockRepositoryMockRecorder) GetDoctorByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorByID", reflect.TypeOf((*MockRepository)(nil).GetDoctorByID), ctx, id)
}

// GetDoctorIDByAccountID mocks base method.
func (m *MockRepository) GetDoctorIDByAccountID(ctx context.Context, accountID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctorIDByAccountID", ctx, accountID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctorIDByAccountID indicates an expected call of GetDoctorIDByAccountID.
func (mr *MockRepositoryMockRecorder) GetDoctorIDByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctorIDByAccountID", reflect.TypeOf((*MockRepository)(nil).GetDoctorIDByAccountID), ctx, accountID)
}

// GetDoctors mocks base method.
func (m *MockRepository) GetDoctors(ctx context.Context, limit int) ([]domain.Doctor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDoctors", ctx, limit)
	ret0, _ := ret[0].([]domain.Doctor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDoctors indicates an expected call of GetDoctors.
func (mr *MockRepositoryMockRecorder) GetDoctors(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDoctors", reflect.TypeOf((*MockRepository)(nil).GetDoctors), ctx, limit)
}

// RemoveAllDoctorToAccountAssignments mocks base method.
func (m *MockRepository) RemoveAllDoctorToAccountAssignments(ctx context.Context, doctorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllDoctorToAccountAssignments", ctx, doctorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllDoctorToAccountAssignments indicates an expected call of RemoveAllDoctorToAccountAssignments.
func (mr *MockRepositoryMockRecorder) RemoveAllDoctorToAccountAssignments(ctx, doctorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllDoctorToAccountAssignments", reflect.TypeOf((*MockRepository)(nil).RemoveAllDoctorToAccountAssignments), ctx, doctorID)
}

// RemoveDoctorAssignment mocks base method.
func (m *MockRepository) RemoveDoctorAssignment(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDoctorAssignment", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDoctorAssignment indicates an expected call of RemoveDoctorAssignment.
func (mr *MockRepositoryMockRecorder) RemoveDoctorAssignment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDoctorAssignment", reflect.TypeOf((*MockRepository)(nil).RemoveDoctorAssignment), ctx, id)
}

// UpdateDoctorStatusByID mocks base method.
func (m *MockRepository) UpdateDoctorStatusByID(ctx context.Context, id string, status domain.DoctorStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDoctorStatusByID", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDoctorStatusByID indicates an expected call of UpdateDoctorStatusByID.
func (mr *MockRepositoryMockRecorder) UpdateDoctorStatusByID(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDoctorStatusByID", reflect.TypeOf((*MockRepository)(nil).UpdateDoctorStatusByID), ctx, id, status)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}
