// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=test/mocks.go -package=test
//

// Package test is a generated GoMock package.
package test

import (
	context "context"
	domain "openhealth/internal/domain"
	event "openhealth/internal/event"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// AddMedicalRecord mocks base method.
func (m *MockRepository) AddMedicalRecord(ctx context.Context, record domain.MedicalRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMedicalRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMedicalRecord indicates an expected call of AddMedicalRecord.
func (mr *MockRepositoryMockRecorder) AddMedicalRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMedicalRecord", reflect.TypeOf((*MockRepository)(nil).AddMedicalRecord), ctx, record)
}

// AddOutboxEvent mocks base method.
func (m *MockRepository) AddOutboxEvent(ctx context.Context, outboxEvent event.OutboxEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOutboxEvent", ctx, outboxEvent)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOutboxEvent indicates an expected call of AddOutboxEvent.
func (mr *MockRepositoryMockRecorder) AddOutboxEvent(ctx, outboxEvent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOutboxEvent", reflect.TypeOf((*MockRepository)(nil).AddOutboxEvent), ctx, outboxEvent)
}

// ArchiveMedicalRecord mocks base method.
func (m *MockRepository) ArchiveMedicalRecord(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveMedicalRecord", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveMedicalRecord indicates an expected call of ArchiveMedicalRecord.
func (mr *MockRepositoryMockRecorder) ArchiveMedicalRecord(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveMedicalRecord", reflect.TypeOf((*MockRepository)(nil).ArchiveMedicalRecord), ctx, id)
}

// GetMedicalRecordByID mocks base method.
func (m *MockRepository) GetMedicalRecordByID(ctx context.Context, id string) (*domain.MedicalRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicalRecordByID", ctx, id)
	ret0, _ := ret[0].(*domain.MedicalRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicalRecordByID indicates an expected call of GetMedicalRecordByID.
func (mr *MockRepositoryMockRecorder) GetMedicalRecordByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicalRecordByID", reflect.TypeOf((*MockRepository)(nil).GetMedicalRecordByID), ctx, id)
}

// GetMedicalRecords mocks base method.
func (m *MockRepository) GetMedicalRecords(ctx context.Context) ([]domain.MedicalRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicalRecords", ctx)
	ret0, _ := ret[0].([]domain.MedicalRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicalRecords indicates an expected call of GetMedicalRecords.
func (mr *MockRepositoryMockRecorder) GetMedicalRecords(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicalRecords", reflect.TypeOf((*MockRepository)(nil).GetMedicalRecords), ctx)
}

// GetMedicalRecordsByAccountID mocks base method.
func (m *MockRepository) GetMedicalRecordsByAccountID(ctx context.Context, accountID string) ([]domain.MedicalRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedicalRecordsByAccountID", ctx, accountID)
	ret0, _ := ret[0].([]domain.MedicalRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedicalRecordsByAccountID indicates an expected call of GetMedicalRecordsByAccountID.
func (mr *MockRepositoryMockRecorder) GetMedicalRecordsByAccountID(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedicalRecordsByAccountID", reflect.TypeOf((*MockRepository)(nil).GetMedicalRecordsByAccountID), ctx, accountID)
}

// UpdateMedicalRecord mocks base method.
func (m *MockRepository) UpdateMedicalRecord(ctx context.Context, record domain.MedicalRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMedicalRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMedicalRecord indicates an expected call of UpdateMedicalRecord.
func (mr *MockRepositoryMockRecorder) UpdateMedicalRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMedicalRecord", reflect.TypeOf((*MockRepository)(nil).UpdateMedicalRecord), ctx, record)
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTransaction mocks base method.
func (m *MockTxManager) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTransaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTransaction indicates an expected call of WithTransaction.
func (mr *MockTxManagerMockRecorder) WithTransaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTransaction", reflect.TypeOf((*MockTxManager)(nil).WithTransaction), ctx, fn)
}

// MockAuthorizationSVC is a mock of AuthorizationSVC interface.
type MockAuthorizationSVC struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationSVCMockRecorder
	isgomock struct{}
}

// MockAuthorizationSVCMockRecorder is the mock recorder for MockAuthorizationSVC.
type MockAuthorizationSVCMockRecorder struct {
	mock *MockAuthorizationSVC
}

// NewMockAuthorizationSVC creates a new mock instance.
func NewMockAuthorizationSVC(ctrl *gomock.Controller) *MockAuthorizationSVC {
	mock := &MockAuthorizationSVC{ctrl: ctrl}
	mock.recorder = &MockAuthorizationSVCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationSVC) EXPECT() *MockAuthorizationSVCMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockAuthorizationSVC) Check(ctx context.Context, tuple domain.Tuple) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, tuple)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockAuthorizationSVCMockRecorder) Check(ctx, tuple any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockAuthorizationSVC)(nil).Check), ctx, tuple)
}
