name: Push To Main

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    name: Build & Push - openhealth-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          context: ./_frontend
          file: ./_frontend/Dockerfile
          image: openhealth-app
          tags: type=raw,value=sha-${{ github.sha }}
          push: true
          build-args: VITE_SITE_URL=https://${{ vars.DOMAIN || 'localhost' }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-backend:
    name: Build & Push - openhealth-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          context: .
          file: ./cmd/openhealth-api/Dockerfile
          image: openhealth-api
          tags: type=raw,value=sha-${{ github.sha }}
          push: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-openfga-init:
    name: Build & Push - openhealth-openfga-init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          context: .
          file: ./scripts/openfga-init/Dockerfile
          image: openhealth-openfga-init
          tags: type=raw,value=sha-${{ github.sha }}
          push: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-seed-db:
    name: Build & Push - openhealth-seed-db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          context: .
          file: ./scripts/seed-db/Dockerfile
          image: openhealth-seed-db
          tags: type=raw,value=sha-${{ github.sha }}
          push: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}

  build-migrate-db:
    name: Build & Push - openhealth-migrate-db
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push
        uses: ./.github/actions/docker-build
        with:
          context: .
          file: ./scripts/migrate-db/Dockerfile
          image: openhealth-migrate-db
          tags: type=raw,value=sha-${{ github.sha }}
          push: true
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
